consumer:
  host: localhost
  username: fiubrother
  password: alwayswatching
  queue: detection_frames

face_detector:
  face_detector:
    type: 'movidius_ssd'
    movidius_id: 0
    longrange: 0
  db:
    host: localhost
    database: big_fiubrother
    username: fiubrother
    password: alwayswatching
  synchronization:
    host: localhost
    port: 2181

publisher_to_classifier:
  host: localhost
  username: fiubrother
  password: alwayswatching
  exchange: fiubrother
  routing_key: detected_faces

publisher_to_scheduler:
  host: localhost
  username: fiubrother
  password: alwayswatching
  exchange: fiubrother
  routing_key: analysed_video_chunks

logging:
  host: localhost
  port: 12201
